# Step 1: Use an optimized OpenJDK image
FROM openjdk:17-jdk-slim

# Step 2: Set working directory
WORKDIR /app

# Step 3: Copy the JAR file (generated by Maven) into the container
# Note: Ensure your pom.xml generates a jar; if the name differs, adjust below
COPY target/*.jar app.jar

# Step 4: Expose the port your app runs on
EXPOSE 8080

# Step 5: Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
